language: go
dist: focal
go:
    - 1.14.x
    - 1.15.x

addons:
  sonarcloud:
    organization: "fathom5"
    token:
      secure: "ewuaZgQaqx4d7x97S2wyW/hwpooI44D6RQGQm3FLkoce+E5EE2sBpOZrEbvQGQ5UUsE6e3kZcbwdhuBPqKnBXxIeepoy+FTAAwgAyA7n416LLBO3FaBpao0hdq9c70mbQ6dTJS3rrU60bCs1WrnWF1K/HwxJLVT14BbXhJBJW4Z5WkLYoMzMC00RtWItG3vLTGQ7bp4iEsIAy6bsP/fpAArKjZg1Qy9Xapn0WVuTvVlh4BwqvEGn1jvCkbiTN4WYqRw2rCHuZQWrOm5sTUkpW7UtBZwKFIqQCvpgrPhQ1aWpx3UgoUfFgNUfGhS258S+4tQRhHEUndpiz/LXWfzAxBz+fjsJJJCPuass0o4JpWYCxJ0lhhn9yDHM8xPbTd11F9bdAnH+CQId+bs85s/uto52OD+QrmW7DgPYCtsDFAf8MshPfShUNyZKrhwiwt2Mfk6A5ElUKtkM221CzSvK6suI5ZB/ftsj4OtPjEf9YQCESE27OwX4tWx8adHgLnoay5UOU74/VYekJapmiRrGUOwqDLMbo59fkuKq5szt7zZOY3frRSwcTfxPRjZTj/4jra3XRSGm9UtjHOeuh6NEDW725XBlR/zdYrRK+fGa/7VF1Du7ABn3B4ZLWWb/1846EIol4tOPMKziaWdug8Zmo07JBbm1jxkj+C0Tk4FYfdE="

before_install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls

install:
    - go get -t -v

script:
- go test -v -covermode=count -coverprofile=profile.cov
- goveralls -coverprofile=profile.cov -service=travis-ci
- sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'