language: go
dist: focal
go:
    - 1.14.x
    # - 1.15.x

env:
  global:
    # SONAR_TOKEN=<travis 2>
    - secure: "uYM+nLaq6hHXqj37h4wkIBrBMSpi9C14u4dZciRbD0wZrye/crjV1QbrQiC7pDCcZPzOwmk7HQRS8d05oX4+dWY6hN7Moik973A6shUm+S/MZj8he0Qy7J+MuGU9DGcQjUA9dxq7PMs+FNj3D477Z2tgSPMPA98PQTxzs3K2i1NoAc7LXnJvrYi6RlszELW4UGEs4cYW1aOfWN0cLEdYMZYlObaCkOc1tOjNpOtEIa1zJNPXO1LeHCfEpq841DrxzSqi8yLZ/GNksAW6SNd2PYQfyzZvut6TZeNW7vBl+0dqOwKIixkBeHVl0Z4uB8kzaf5p8v0vK+QSjnMmMsmEkdLKqdl0rQWkzqKcVNwgTnUYiCLFyYXybQ+/gMsRPfcn2gt7WRliPd3+oC301v68B3Lb8Wo7D2lofgvNu7AZOyWP+rpPBZhFeEvXMvIurLIXKtjPJNxcaXdLyQtRy5Z/Y7kyf28JD2ZUENWgDo4eaCXFHui6ZkeL0t4jcQ7mYlqP7cOJtCKi/46RIO6tIpE6Ux9PTR++SPQCnGOjzi2VTgt2+lb0yPI/TW59lC6mh6wr3YJHHwXB8kW15RF5bq01en5mWsJt8g5s40/t+FCVmZDKmxdTsfUcl75+Pcu8WjZL5qQSjEGFfHGUNyvdsy7IJFGMp4Drf2zMf3j3cGhP4Hw="

addons:
  sonarcloud:
    organization: "fathom5"
    token: ${SONAR_TOKEN}

before_install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls

install:
    - go get -t -v

script:
- go test -v -covermode=count -coverprofile=profile.cov
- go test -json > gotest-report.json
- go vet -json > govet-report.json
- goveralls -coverprofile=profile.cov -service=travis-ci
- sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'