language: go
dist: focal
go:
    - 1.14.x
    - 1.15.x

addons:
  sonarcloud:
    organization: "fathom5"
    token:
      - secure: "CIypLNW0wY0OV3pYprIXioKF48zVdUw3yd3pmGpBfDFAAN8fWa+TAI3Yyy4IrB88xFYCs4iQjvzMVhLE7vzqr4w6CTiLG42Uu+2pa2ylh/X0b4jwR1G5c07uh5FVnfqWc81Rf9MKENa/VGVcyu0hx3NGSI2qbi/WpiCJukZolI16f9FCHxY434N7jAXDXlAvahG55EFehXVX31oNIOZcZw6JpH5oSwUxDH4A/WjSpV7vKmnIhYCWaNhWqciJ6SNzhnG/PeQST9UYpgmZaio9gvj7y+z3dQVMttCnwInNUFSUp4GA3kKNp7bq5PN5V5Wy5DZ2nq4qeK5UERhKleAonSkpIeYjYrpihjRgKp4UvdNeh1esN328H2IuRSR1tCyac0Lx1SVW1Ui0ZDHatqlMBkYpF3j73hts7h8M4MA+Uq3Q7zS5G4ol3fgq1Ss0zysBQJzB0z4jKNG3m5zFRyiWnT6EykmSW02+lDWAVbrvwbn7na3tK/Tc/7QKYS3bUuVljOMHLai4O7t3VPoTmfOlMfWmcQvVRnJVstyVh/fK1JDQVRyKPXTqk/BxYkBX4oUcvD08MM+r8sc9SfV4yOo49zhsD/+Dd5V6dirGdMyC0SIaxCa1C1uWTmLFcnjEEpXJGvfwErY0tzdd7Nfe7azEiZhYuSs61sea4u3bdlmrBww="

before_install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls

install:
    - go get -t -v

script:
- go test -v -covermode=count -coverprofile=profile.cov
- goveralls -coverprofile=profile.cov -service=travis-ci
- sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'